Nomina/urls.py
from django.conf.urls import patterns, url

from Nomina.views import *


urlpatterns = patterns('',

    url(r'^cargo/$',GestionCargos),
    url(r'^empleado/$',GestionEmpleados),
    url(r'^editaEmpleado/(?P<idEmpleado>\d+)',EditaEmpleados),
    url(r'^login/$',Login,name='login'),
    url(r'^usuarios/$',GestionUsuario),
    url(r'^logOut/$',logOut),

)

Ventas/urls.py
from django.conf.urls import patterns, url
from Ventas.views import *


urlpatterns = patterns('',

    url(r'^inicioVentas/$',InicioVentas),
    url(r'^ventas/$',GestionVentas),
    url(r'^detalleVentas/(?P<idVenta>\d+)',GestionDetalleVentas),
    url(r'^consultaPrecioProducto/$',consultaValorProducto),
    url(r'^guardaVenta/$',GuardarVenta),
    url(r'^consultaCosto/$',consultaCostoProducto),
    url(r'^editaDetVenta/(?P<idDetVenta>\d+)',EditaDetalleVentas),

    url(r'^pedido/(?P<idcliente>\d+)',GestionPedidos),
    url(r'^editarDetpedido/(?P<idDetpedido>\d+)',EditarDetallePedido),
    url(r'^borrarPedido/(?P<idpedido>\d+)',BorrarPedidos),
    url(r'^templateTipoPedido/$',TemplateTipoPedido),
    url(r'^consultaTipoPedido/$',ReporteTipoPedido),
    url(r'^consultaTipoPedidoContado/$',ReporteTipoPedidoContado),
    url(r'^detallePedido/(?P<idpedido>\d+)',GestionDetallePedido),
    url(r'^BorrardetallePedido/(?P<idpedido>\d+)',BorrarDetallePedido),
    url(r'^guardarPedido/$',GuaradarPedido),
    url(r'^verificarPrecioPedido/$',VerificarPrecioPedido),
    url(r'^tipoProducto/$',TipoProducto),

    #url(r'^pedidoPdf/(?P<idpedido>\d+)',ReportePedido),
    url(r'^listaPrecios/$',GestionLista),
    url(r'^detalleLista/(?P<idLista>\d+)',GestionDetalleLista),
    url(r'^editaListaPrecios/(?P<idLista>\d+)',EditaListaPrecios),
    url(r'^editaLista/(?P<idDetLista>\d+)',EditaListas),
    url(r'^borraDetListaPrecios/(?P<idDetLista>\d+)',borrarItemListaPrecios),

    url(r'^ventaPunto/$',PuntoVenta),
    url(r'^detalleVentaPunto/(?P<idVenta>\d+)',DetallePuntoVenta),
    url(r'^editaVentaPunto/(?P<idDetVenta>\d+)',EditaPuntoVenta),
    url(r'^eliminaVentaPunto/(?P<idDetVenta>\d+)',EliminaPuntoVenta),
    url(r'^valorProdVenta/$',ValorProdVenta),
    url(r'^anulaVenta/$',AnulaVentas),

    url(r'^caja/$',GestionCaja),
    url(r'^editaCaja/(?P<idCaja>\d+)',EditaCaja),

    url(r'^cobrar/$',CobrarVenta),

    url(r'^retiro/$',GestionRetiros),
    url(r'^ImprimirRetiro/$',ImprimirRetiro),

    url(r'^devoluciones/$',GestionarDevolucion),
    url(r'^detalleDevoluciones/(?P<idDev>\d+)',GestionDetalleDevolucion),
    url(r'^GuardarDevolucion/$',GuardarDevolucion),

    url(r'^templateAZ/$',TemplateAZ),
    url(r'^reporteAZ/$',ReporteAZ),

    url(r'^templateReporteVentaNorte/$',TemplateReporteVentaNorte),
    url(r'^reporteVentaNorte/$',ReporteVentaNorte),
    url(r'^templateReporteVentaDiaria/$',TemplateReporteVentaDiaria),
    url(r'^reporteVentaDiaria/$',ReporteVentaDiaria),

    url(r'^configPuntos/$',GestionConfigPuntos),
    url(r'^editaConfigPuntos/(?P<idConfig>\d+)',EditaConfigPuntos),

    url(r'^TemplateListaVentaNorte/$',TemplateRepListVentasNorte),
    url(r'^reporteListaVentaNorte/$',RepListVentasNorte),
)

porkisoft/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from Inventario.views import inicio,home
from  Ventas.views import PuntoVenta
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$',inicio),
    url(r'^infoGral/$',home),
    url(r'^VentasNorte/',PuntoVenta),

    url(r'^inventario/', include('Inventario.urls')),
    url(r'^telemercadeo/', include('Telemercadeo.urls')),
    url(r'^nomina/', include('Nomina.urls')),
    url(r'^ventas/', include('Ventas.urls')),
    url(r'^fabricacion/', include('Fabricacion.urls')),


    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

Ventas/models.py
from django.db import models
from Telemercadeo.models import *
from Inventario.models import Bodega,Producto,SubProducto
from Nomina.models import Empleado

# Create your models here.
class ListaDePrecios(models.Model):
    tipo = (
    ('Restaurante', 'Restaurante'),
    ('Punto', 'Punto'),
    ('Contrato', 'Contrato'),
    )
    codigoLista = models.AutoField(primary_key=True)
    fecha = models.DateField(verbose_name='Fecha')
    nombreLista = models.CharField(max_length=50,verbose_name='Nombre')
    tipoLista = models.CharField(verbose_name='Tipo',max_length=15,choices=tipo)
    bodega = models.ForeignKey(Bodega)


    def __unicode__(self):
        cadena = '%d | %s'%(self.codigoLista,self.nombreLista)
        return cadena

class DetalleLista(models.Model):
    lista = models.ForeignKey(ListaDePrecios,verbose_name='Lista')
    productoLista = models.ForeignKey(Producto,verbose_name='Producto')
    costoKilo = models.DecimalField(max_digits=9, decimal_places=3,verbose_name='Costo Kilo',null= True,default=0)
    precioVenta = models.IntegerField(verbose_name='Precio Venta')


class Venta(models.Model):
    jornadas = (
    ('AM', 'AM'),
    ('PM', 'PM'),
    )
    numeroVenta = models.AutoField(primary_key=True, verbose_name='Numero Factura')
    fechaVenta = models.DateField(verbose_name='Fecha')
    lista = models.ForeignKey(ListaDePrecios,null=True,blank=True)
    bodega = models.ForeignKey(Bodega)
    TotalRegistradora = models.IntegerField(verbose_name='Total Registradora',default=0)
    TotalVenta = models.IntegerField(verbose_name='Total Venta',default=0)
    TotalCredito = models.IntegerField(verbose_name='Total Credito',default=0)
    TotalContado = models.IntegerField(verbose_name='Total Contado',default=0)
    efectivo = models.IntegerField(verbose_name='Efectivo',default=0)
    descuadre = models.IntegerField(verbose_name='Descuadre',default=0)
    residuo = models.IntegerField(default=0)
    jornada = models.CharField(verbose_name='Jornada',max_length=5,choices=jornadas)
    restaurante = models.BooleanField(default=False,verbose_name='Restaurantes')
    guardado = models.BooleanField(default=False,verbose_name='Guardado')

    def __unicode__(self):
        return self.numeroVenta

class DetalleVenta (models.Model):
    venta = models.ForeignKey(Venta)
    peso = models.DecimalField(max_digits=9, decimal_places=3,verbose_name='Peso en Venta',null= True,default=0)
    unidades = models.IntegerField(verbose_name='Unidades en Venta',null= True,default=0)
    productoVenta = models.ForeignKey(Producto,null=True)
    vrUnitario = models.IntegerField(verbose_name='Vr.Unitario', default=0)
    vrTotal = models.IntegerField(verbose_name='Vr.Total',default=0)
    credito = models.BooleanField(verbose_name='Credito',default=False)
    contado = models.BooleanField(verbose_name='Contado',default=False)



class Pedido(models.Model):
    numeroPedido = models.AutoField(primary_key=True, verbose_name='Numero Pedido')
    numeroFactura = models.BigIntegerField(verbose_name='Factura No.',default=0)
    fechaPedido = models.DateField(verbose_name='Fecha')
    listaPrecioPedido = models.ForeignKey(ListaDePrecios,verbose_name='Lista Precios')
    cliente = models.ForeignKey(Cliente)
    NombreCliente = models.CharField(max_length=100,default=0)
    nitCliente = models.CharField(max_length=50,default=0)
    empleado = models.ForeignKey(Empleado)
    bodega = models.ForeignKey(Bodega)
    TotalVenta = models.IntegerField(verbose_name='Total Venta',default=0)
    credito = models.BooleanField(verbose_name='Credito',default=False)
    contado = models.BooleanField(verbose_name='Contado',default=False)
    guardado = models.BooleanField(default=False,verbose_name='Guardado')

    def __unicode__(self):
        return self.numeroPedido

class DetallePedido (models.Model):
    pedido = models.ForeignKey(Pedido)
    productoPedido = models.ForeignKey(Producto,null=True,blank=True)
    subproducto = models.ForeignKey(SubProducto, null=True)
    pesoPedido = models.DecimalField(max_digits=9, decimal_places=3,verbose_name='Cantidad',null= True,default=0)
    unidadesPedido = models.IntegerField(verbose_name='Unidades',null= True,default=0)
    vrUnitario = models.IntegerField(verbose_name='Vr.Unitario', default=0)
    vrTotalPedido = models.IntegerField(verbose_name='Vr.Total',default=0)
    estado = models.BooleanField(verbose_name='Estado',default=False)

class VentaPunto(models.Model):
    jornadas = (
    ('AM', 'AM'),
    ('PM', 'PM'),
    )

    numeroVenta = models.AutoField(primary_key=True, verbose_name='Codigo')
    fechaVenta = models.DateField(verbose_name='Fecha')
    puntoVenta = models.ForeignKey(Bodega)
    factura = models.IntegerField(verbose_name='No.Factura',default=0)
    encargado = models.ForeignKey(Empleado,verbose_name='Encargado')
    jornada = models.CharField(verbose_name='Jornada',max_length=5,choices=jornadas)
    TotalVenta = models.IntegerField(verbose_name='Total Venta',default=0)
    cliente = models.ForeignKey(Cliente,blank=True,null=True,verbose_name='Cliente')
    restaurante = models.BooleanField(verbose_name='Restaurante',default=False)
    guardado = models.BooleanField(default=False,verbose_name='Guardado')
    anulado = models.BooleanField(default=False,verbose_name='Anulado')

    def __unicode__(self):
        return self.numeroVenta

class DetalleVentaPunto (models.Model):
    venta = models.ForeignKey(VentaPunto)
    productoVenta = models.ForeignKey(Producto,null=True,blank=True,verbose_name='Producto')
    pesoVentaPunto = models.DecimalField(max_digits=9, decimal_places=3,verbose_name='Cantidad',null= True)
    unidades = models.IntegerField(verbose_name='Unidades',null= True,default=0)
    vrUnitarioPunto = models.IntegerField(verbose_name='Vr.Unitario', default=0)
    vrTotalPunto = models.IntegerField(verbose_name='Vr.Total',default=0)


class Caja (models.Model):
    jornadas = (
    ('AM', 'AM'),
    ('PM', 'PM'),
    )
    numeroCaja = models.AutoField(primary_key=True, verbose_name='Numero Caja')
    fechaCaja = models.DateField(verbose_name='Fecha')
    jornada = models.CharField(verbose_name='Jornada',max_length=5,choices=jornadas)
    encargado = models.ForeignKey(Empleado,verbose_name='Encargado')
    base = models.IntegerField(verbose_name='Base',default=0)
    TotalVenta = models.IntegerField(verbose_name='Venta',default=0)
    TotalRetiro = models.IntegerField(verbose_name='Venta',default=0)
    TotalRestaurante = models.IntegerField(verbose_name='Venta',default=0)
    TotalCaja = models.IntegerField(verbose_name='Caja',default=0)
    TotalEfectivo = models.IntegerField(verbose_name='Efectivo',default=0)
    TotalResiduo = models.IntegerField(verbose_name='Residuo',default=0)

class Retiros (models.Model):
    jornadas = (
    ('AM', 'AM'),
    ('PM', 'PM'),
    )

    fechaRetiro = models.DateField(verbose_name='Fecha',auto_now=True)
    encargado = models.ForeignKey(Empleado,verbose_name='Encargado')
    jornada = models.CharField(verbose_name='Jornada',max_length=5,choices=jornadas)
    nombreEncargado = models.CharField(verbose_name='Nombre Empleado',max_length=50,blank=True)
    cantidad = models.IntegerField(verbose_name='Cantidad',default=0)
    observacion = models.TextField(verbose_name='Observacion')
    guardado = models.BooleanField(default=False,verbose_name='Guardado')


class Devolucion (models.Model):

    fechaDevolucion = models.DateField(verbose_name='Fecha',auto_now=True)
    encargado = models.ForeignKey(Empleado,verbose_name='Encargado')
    observacion = models.TextField(verbose_name='Observacion')
    guardado = models.BooleanField(default=False,verbose_name='Guardado')

    def __unicode__(self):
        return self.id

class DetalleDevolucion (models.Model):

    devolucion = models.ForeignKey(Devolucion)
    productoDev = models.ForeignKey(Producto,verbose_name='Producto')
    pesoProducto = models.DecimalField(max_digits=9, decimal_places=3,verbose_name='Peso',null= True,default=0)
    cantidad = models.IntegerField(verbose_name='Und',default=0)

class ConfiguracionPuntos(models.Model):
    jornadas = (
    ('AM', 'AM'),
    ('PM', 'PM'),
    )
    fecha = models.DateField(verbose_name='Fecha Actualizacion')
    bodega = models.ForeignKey(Bodega)
    nombreConfiguracion = models.CharField(verbose_name='Nombre',max_length=50)
    cajero = models.ForeignKey(Empleado,verbose_name='Cajero')
    jornada = models.CharField(verbose_name='Jornada',max_length=5,choices=jornadas)
    inicia = models.IntegerField(verbose_name='vr Inicial',default=0)
    actual = models.IntegerField(verbose_name='vr actual',default=0)
    finaliza = models.IntegerField(verbose_name='vr Final',default=0)
    consecutivoZ = models.IntegerField(verbose_name='ConsecZ',default=0)

class prueba(models.Model):
    prueba = models.CharField(max_length=10)

porkisoft/porkisoft/models.py
from django.db import models
# Create your models here.

class Producto(models.Model):
    nombreProducto = models.CharField(verbose_name = 'Nombre Producto',max_length=50)
    pesoProducto = models.DecimalField(verbose_name = 'Peso Producto (grs)',max_digits=9, decimal_places=3)
    costoProducto = models.IntegerField(verbose_name = 'Costo Producto')
    vrCompraProducto = models.IntegerField(verbose_name = 'Valor de Compra')
    gravado = models.BooleanField(verbose_name = 'Gravado')
    utilidadProducto = models.IntegerField(verbose_name = 'Ulilidad')
    rentabilidadProducto = models.IntegerField(verbose_name = 'Rentabilidad')
    refrigerado = models.BooleanField(verbose_name = 'Refrigerado')
    congelado = models.BooleanField(verbose_name = 'Congelado')
    
    def __unicode__(self):
        return self.nombreProducto
        

porkisoft/templates/Ventas/GestionDetalleListas.html
{% extends 'base.html' %}

{% block titulo %}Detalle Lista{% endblock titulo %}
{% block mensajes %}Detalle de Lista de precios {% endblock mensajes %}
{% block contenido %}
<a id="nuevo" href="#"><input type="button" value="Nuevo" class="btn btn-primary"></a>
<br/><br/><br/>
    <table  class="table-striped" >

        <thead >
        <tr>
            <th>Codigo</th>
            <th>Fecha</th>
            <th>Nombre</th>

        </tr>
        </thead>

        <tr>
            <td>{{ lista.codigoLista }}</td>
            <td>{{ lista.fecha }}</td>
            <td>{{ lista.nombreLista }}</td>

        </tr>

    </table>
    <br/><br/>
    <table id="listaDePrecios" class="table-striped" >

        <thead >
        <tr>
            <th>Codigo Venta</th>
            <th>Producto</th>
            <th>Costo Kilo</th>
            <th>Precio Venta</th>
            <th>Acciones</th>

        </tr>
        </thead>
        {% for detalle in detalleListas %}
        {% if detalle.costoKilo > detalle.precioVenta %}
            <tr style="color: red">
        {% else %}
            <tr style="color: green">
        {% endif %}
            <td>{{ detalle.productoLista.numeroProducto }}</td>
            <td>{{ detalle.productoLista.nombreProducto }}</td>
            <td>{{ detalle.costoKilo }}</td>
            <td>{{ detalle.precioVenta }}</td>

            <td>
                <a href="{% url 'Ventas.views.EditaListas' detalle.id %}">Actualizar</a>
                <a href="{% url 'Ventas.views.borrarItemListaPrecios' detalle.id %}">Borrar</a>
            </td>

        </tr>
            {% empty %}
            <tr>
                <td colspan="9">
                   Ningun registro para mostrar
                </td>
            </tr>

        {% endfor %}
    </table>
    <form method="post" class="form-horizontal">{% csrf_token %}
         <fieldset id="agregarBodega">
             <legend>Venta<a id="cerrar" href="#"><img src="{{ STATIC_URL }}img/cerrar.png"/></a></legend>

                  {{ formulario }}

              <br/>
          <input class="btn btn-default" value="Guardar" type="submit">
         </fieldset>
     </form>
{% endblock contenido %}

porkisoft/templates/Ventas/GestionDetallePedido.html
{% extends plantilla %}

{% block titulo %}{{ pedido.cliente.nombreCliente }}{% endblock titulo %}
{% block mensajes %}Detalles del pedido{% endblock mensajes %}
{% block contenido %}
<a id="nuevo" href="#"><input type="button" value="Nuevo" class="btn btn-primary"></a>
<a  onclick="GuardarPedido({{ pedido.numeroPedido }})" href="#"><input type="button" value="Guardar" class="btn btn-warning"></a>
    <br/><br/><br/>
    <table class="table-striped" >

        <thead >
        <tr>
            <th>Factura</th>
            <th>Fecha y hora</th>
            <th>Lista Precios</th>
            <th>Empleado</th>
            <th>Cliente</th>
            <th>Bodega</th>
            <th>Tipo</th>
            <th>Vr.Pedido</th>
            <th>Guardado</th>


        </tr>
        </thead>
            <tr>
                <td>{{ pedido.numeroFactura }}</td>
                <td>{{ pedido.fechaPedido }}</td>
                <td id="listaPrecios">{{ pedido.listaPrecioPedido.codigoLista }}</td>
                <td>{{ pedido.empleado }}</td>
                <td>{{ pedido.cliente }}</td>
                <td id="bodegaPedido">{{ pedido.bodega.codigoBodega}}</td>
                {% if pedido.credito == True %}
                    <td id="tipoPedido">Credito</td>
                {% else %}
                    <td id="tipoPedido" >Contado</td>
                {% endif %}

                <td>{{ pedido.TotalVenta }}</td>
                {% if pedido.guardado == True %}
                    <td id="tipoPedido">Si</td>
                {% else %}
                    <td id="tipoPedido" >No</td>
                {% endif %}
            </tr>

    </table>
    <br/>
    <table class="table-striped" >

        <thead>
        <tr>
            <th>Codigo</th>
            <th>Nombre</th>
            <th>Telefono</th>
            <th>Direccion</th>


        </tr>
        </thead>

            <tr>
                <td>{{ pedido.cliente.codigoCliente }}</td>
                <td>{{ pedido.cliente.nombreCliente }}</td>
                <td>{{ pedido.cliente.telefonoCliente }}</td>
                <td>{{ pedido.cliente.direccionCliente }}</td>

            </tr>

    </table>
    <br/>

    <table class="table-striped" >

        <thead >
        <tr>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Vr.Unitario</th>
            <th>Vr. Total</th>
            <th>Accion</th>

        </tr>
        </thead>
        {% for det  in detPedido %}
        <tr>
            <td>{{ det.productoPedido }}</td>
            <td>{{ det.pesoPedido|floatformat }}</td>
            <td>{{ det.vrUnitario }}</td>
            <td>{{ det.vrTotalPedido }}</td>
            <td><a href="{% url 'Ventas.views.BorrarDetallePedido' det.id %}">Borrar</a>
                <a href="{% url 'Ventas.views.EditarDetallePedido' det.id %}">Editar</a>
            </td>

        </tr>

            {% empty %}
            <tr>
                <td colspan="9" >
                   Ningun registro para mostrar
                </td>
            </tr>

        {% endfor %}


    </table>
    <form method="post" class="form-horizontal">{% csrf_token %}
         <fieldset id="agregarBodega">
             <legend>Pedido<a id="cerrar" href="#"><img src="{{ STATIC_URL }}img/cerrar.png"/></a></legend>
             <label for="productoPedido">Producto</label><select id="productoPedido" name="prodPedido">
                 {% for lista in ListadoPrecios %}
                     <option value="{{ lista.productoLista.codigoProducto }}">{{ lista.productoLista.numeroProducto }} --{{ lista.productoLista.nombreProducto }}</option>
                {% endfor %}
             </select>

                  {{ formulario }}

              <br/>
          <input class="btn btn-primary" value="Guardar" type="submit">

         </fieldset>
     </form>
{% endblock contenido %}

porkisoft/templates/Ventas/GestionPedido.html
{% extends plantilla %}

{% block titulo %}Pedidos{% endblock titulo %}
{% block mensajes %}Listado de Pedidos de {{ cliente }}{% endblock mensajes %}
{% block contenido %}
<a id="nuevo" href="#"><input type="button" value="Nuevo" class="btn btn-primary"></a>

    <br/><br/><br/>
    <table id="tablabodegas" class="table-striped" >

        <thead >
        <tr>
            <th>Factura</th>
            <th>Fecha y hora</th>
            <th>Lista Precios</th>
            <th>Empleado</th>
            <th>Cliente</th>
            <th>Bodega</th>
            <th>Tipo</th>
            <th>Vr. Pedido</th>
            <th>Guardado</th>
            <th>Accion</th>

        </tr>
        </thead>
        {% for pedido in pedidos %}
        <tr>
            <td>{{ pedido.numeroFactura }}</td>
            <td>{{ pedido.fechaPedido }}</td>
            <td>{{ pedido.listaPrecioPedido }}</td>
            <td>{{ pedido.empleado }}</td>
            <td>{{ pedido.cliente }}</td>
            <td>{{ pedido.bodega}}</td>
            {% if pedido.credito == True %}
                <td id="tipoPedido">Credito</td>
            {% else %}
                <td id="tipoPedido" >Contado</td>
            {% endif %}

            <td> {{ pedido.TotalVenta }} </td>
            {% if pedido.guardado == True %}
                    <td id="tipoPedido">Si</td>
                {% else %}
                    <td id="tipoPedido" >No</td>
                {% endif %}
            <td>
                <a  href="{% url 'Ventas.views.GestionDetallePedido' pedido.numeroPedido %}">Detalles</a>
                <a  href="{% url 'Ventas.views.BorrarPedidos' pedido.numeroPedido %}">Borrar</a>
            </td>

        </tr>
            {% empty %}
            <tr>
                <td colspan="9">
                   Ningun registro para mostrar
                </td>
            </tr>

        {% endfor %}
    </table>
    <form method="post" class="form-horizontal">{% csrf_token %}
         <fieldset id="agregarBodega">
             <legend>Pedido<a id="cerrar" href="#"><img src="{{ STATIC_URL }}img/cerrar.png"/></a></legend>

                  {{ formulario }}

              <br/>
          <input class="btn btn-default" value="Guardar" type="submit">
         </fieldset>
     </form>
{% endblock contenido %}

porkisoft/templates/Ventas/TemplateDetalleVentaPunto.html
{% extends 'PuntoVentaNorte.html' %}

{% block titulo %}::Porkilandia::{% endblock titulo %}
{% block mensajes %}
        <div id="direccion">
        Dir: {{ venta.puntoVenta.direccionBodega }} Tel:{{ venta.puntoVenta.telefonoBodega }}
        </div>
{% endblock mensajes %}
{% block contenido %}
    <!--<input type="button"  value="Imprimir" class="btn btn-success">
    <input type="button" value="Cobrar" class="btn btn-warning">
    -->

    <a id="imprimeRecibo" onclick="ImprimirRecibo()" href="#"><img src="{{ STATIC_URL }}img/printer1.png" alt="" /></a><br/>
    <a id="cobraVenta" onclick="Cobrar()" href="#"><img src="{{ STATIC_URL }}img/dinero.png" alt="" /></a>


    <div id="calculaVuelto">
        <label for="totalCompra">Esta en Venta : </label><input id="totalCompra" type="text"/>
        <label for="efectivo">Efectivo</label><input id="efectivo" type="text"/>
        <label for="regreso">Regreso</label><input id="regreso" type="text"/>
    </div>

<br/><br/><br/><br/>
    <table id="tablaVentaPunto" class="table-striped" >

        <thead >
        <tr>
            <th>Codigo</th>
            <th>Factura</th>
            <th>Fecha</th>
            <th>Encargado</th>
            <th>Jornada</th>
            <th>Total Venta</th>
            <th>Total Gravado</th>
            <th>Guardado</th>

        </tr>
        </thead>
            <td id="NumVenta">{{ venta.numeroVenta }}</td>
            <td id="numFactura">{{ venta.factura }}</td>
            <td id="FechaVenta" >{{ venta.fechaVenta }}</td>
            <td id="NomEncargado">{{ venta.encargado }}</td>
            <td>{{ venta.jornada }}</td>
            <td id="totalVentaDet">{{ venta.TotalVenta }}</td>
            <td id="Totalgravado" >{{ totalGravado | floatformat }}</td>
            {% if venta.guardado == True %}
                <td id="guardado">Si</td>
            {% else %}
                <td id="guardado">No</td>
            {% endif %}

    </table>
    <br/>
    <div id="recibo">
    <div id="Cabecera"></div>

     <br/>
        <table id="tablaDetalleVentaPunto" class="table-striped" >

        <thead >
        <tr>

            <th>Producto</th>
            <th>Cantidad</th>
            <th>Vr.Unitario</th>
            <th>Vr.Total</th>
            <th>Acciones</th>


        </tr>
        </thead>
        {% for detventa in detVentas %}
            <tr>
            <td>{{ detventa.productoVenta.nombreProducto }}</td>
            <td>{{ detventa.pesoVentaPunto|floatformat }}</td>
            <td>$ {{ detventa.vrUnitarioPunto }}</td>
            <td>$ {{ detventa.vrTotalPunto }}</td>
            {% if venta.guardado == True %}
                <td></td>
            {% else %}
                <td>
                <!--<a href="{% url 'Ventas.views.EditaPuntoVenta' detventa.id %}">Editar</a>-->
                <a href="{% url 'Ventas.views.EliminaPuntoVenta' detventa.id %}" style="color: red">Borrar</a>
                </td>
            {% endif %}


        </tr>
            {% empty %}
            <tr>
                <td colspan="9">
                   Ningun registro para mostrar
                </td>
            </tr>

        {% endfor %}
    </table>
        <br/><br/>

    <br/>
    <div id="piePagina"></div>

    </div>

    <form id="FormularioVentaPunto" method="post" class="form-horizontal">{% csrf_token %}
         <fieldset id="FrmVenta">
             <legend>Venta</legend>
             <label for="id_productoVenta">Productos</label><select id="id_productoVenta" name="ProductoVentaPunto">
                 {% for lista in ListadoPrecios %}
                     <option value="{{ lista.productoLista.codigoProducto }}">{{ lista.productoLista.numeroProducto }} --{{ lista.productoLista.nombreProducto }}</option>
                {% endfor %}
             </select>

                 {{ formulario }}

              <br/>
          <input class="btn btn-success" value="Al Listado" type="submit">
         </fieldset>
     </form>
{% endblock contenido %}